\echo Creating Table TRADE
CREATE TABLE TRADE (
   ID 			SERIAL,
   TRD_DT		DATE 		NOT NULL,
   TYPE			TEXT		NOT NULL,   
   MONTH		TEXT		NOT NULL,
   NAME 		TEXT 		NOT NULL,   
   TRD_QTY		INT 		NOT NULL,
   ENT_DT		DATE 		NOT NULL,
   COMMENTS		TEXT,
   CONSTRAINT 	pk_DT_Contract 	PRIMARY KEY (TRD_DT, TYPE, MONTH, NAME)
);

